### ISSUE TITLE
Deploying to Android fails with zipalign error

### ISSUE THREAD

**Issue by davidortinau** [xamarin/xamarin-android#1519]
_From @johnshardman on April 4, 2018 10:25_

Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
After upgrading Visual Studio to 15.6, deployment of app to Android (physical devices and emulators) failed with a zipalign error.

### Steps to Reproduce

1. Check the "Generate one package (.apk) per selected ABI" option in the Android project properties.
2. Hit F5

### Expected Behavior

App should build, deploy and run in debug mode.

### Actual Behavior

Deployment error reported:

AndroidZipAlign Task
Alignment: 4
Source: G:\tfs\MyApp\Top\MyApp.Android\obj\Debug\android\bin\com.MyApp.MyApp-arm64-v8a.apk
DestinationDirectory: bin\Debug\
C:\ProgramFiles\Android\AndroidSDK\build-tools\25.0.2\zipalign.exe 4 "G:\tfs\MyApp\Top\MyApp.Android\obj\Debug\android\bin\com.MyApp.MyApp-arm64-v8a.apk" "bin\Debug\com.MyApp.MyApp-arm64-v8a-Signed.apk" 
Output file 'bin\Debug\com.MyApp.MyApp-arm64-v8a-Signed.apk' exists
"zipalign.exe" exited with code 1.
Done executing task "AndroidZipAlign" -- FAILED

### Basic Information

VS 15.6
XF 2.4.0.38779

I'm not the only one seeing this. @batmaci has also reported it at https://forums.xamarin.com/discussion/comment/325764

_Copied from original issue: xamarin/Xamarin.Forms#2243_

**Comment by dellis1972** [comment]
@davidortinau I am unable to repo this on our master branch on Mac. I will try on windows d15-7. Failing that can you provide diagnostic output from your repo (and even the repo project itself) to make sure we are using the correct setup.

**Comment by dellis1972** [comment]
@davidortinau  There are a number of variables in this it seems (as I am unable to repo at all or master or d15-7). 
Are they using `apksigner` ? Is it turned off? what are the values for `AndroidSupportedAbis`.
We could really use some diagnostic build output that would clear allot of those questions up. 

While I am tempted to implement @atsushieno's suggestion, until I can repo we'd just be guessing.

**Comment by RobertFrancis** [comment]
Here is a project that is broken with this issue. If it builds and deploys to a device correctly, make a code change eg `string debug = ""; `. Build and redeploy and you should be able to reproduce the zip align error. This project also creates corrupt abi's when trying to package them.

- Generate one package (.apk) per selected ABI (Checked)
- Advanced > Supported ABI's - armeabi (Checked), armeabli-v7a (Checked), x86 (Checked), arm64-v8a (Unchecked), x86_64 (Unchecked)

**Comment by dellis1972** [comment]
@RobertFrancis thanks for the info, however I already tried that exact scenario and it worked here.
Do you have the diagnostic build output from that process? if so can you pop it up on gist.guthub.com so we can take a look at the output?

**Comment by RobertFrancis** [comment]
Is this what you mean 

`Build started 09/04/2018 13:53:10.
__________________________________________________
Project "/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj" (Install target(s)):

Target _SetLatestTargetFrameworkVersion:
    Found Java SDK version 1.8.0.
Target _ValidateAndroidPackageProperties:
      PackageName: com.companyname.testHelloworld2
Target _ResolveMonoAndroidSdks:
    MonoAndroid Tools: /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/
    Android Platform API level: 23
    TargetFrameworkVersion: v6.0
    Android NDK: /Users/myProjectFolder/Library/Developer/Xamarin/android-ndk/android-ndk-r14b/
    Android SDK: /Users/myProjectFolder/Library/Developer/Xamarin/android-sdk-macosx/
    Android SDK Build Tools: /Users/myProjectFolder/Library/Developer/Xamarin/android-sdk-macosx/build-tools/27.0.3/
    Java SDK: /usr/
Target _GetPrimaryCpuAbi:
    _PrimaryCpuAbi=arm64-v8a
Target _CheckInstantRunCondition:
    Dex Fast Deployment Enabled: False
Target _SetupInstantRun:
    Android Java Class for Fast Deployment: 
Target _SetupApplicationJavaClass:
    Application Java class: android.app.Application
Target _XamarinAndroidBuildResourceRestore:
    Reference has already had resources merged, skipping due to: obj/Debug/XbdMerge/Xamarin.Android.Support.Annotations.dll.stamp
Target _XamarinAndroidBuildAarRestore:
    Reference has already had resources merged, skipping due to: obj/Debug/XbdMerge/Xamarin.Android.Support.Compat.dll.stamp
    Reference has already had resources merged, skipping due to: obj/Debug/XbdMerge/Xamarin.Android.Support.Core.UI.dll.stamp
    Reference has already had resources merged, skipping due to: obj/Debug/XbdMerge/Xamarin.Android.Support.Core.Utils.dll.stamp
    Reference has already had resources merged, skipping due to: obj/Debug/XbdMerge/Xamarin.Android.Support.Media.Compat.dll.stamp
    Reference has already had resources merged, skipping due to: obj/Debug/XbdMerge/Xamarin.Android.Support.Fragment.dll.stamp
    Reference has already had resources merged, skipping due to: obj/Debug/XbdMerge/Xamarin.Android.Support.Vector.Drawable.dll.stamp
    Reference has already had resources merged, skipping due to: obj/Debug/XbdMerge/Xamarin.Android.Support.Animated.Vector.Drawable.dll.stamp
    Reference has already had resources merged, skipping due to: obj/Debug/XbdMerge/Xamarin.Android.Support.v7.AppCompat.dll.stamp
Target _ResolveLibraryProjectImports:
  Skipping target "_ResolveLibraryProjectImports" because all output files are up-to-date with respect to the input files.
Target _BuildLibraryImportsCache:
  Skipping target "_BuildLibraryImportsCache" because all output files are up-to-date with respect to the input files.
Target _BuildAdditionalResourcesCache:
  Skipping target "_BuildAdditionalResourcesCache" because all output files are up-to-date with respect to the input files.
Target _CreateAdditionalResourceCache:
  Skipping target "_CreateAdditionalResourceCache" because it has no outputs.
Target _GenerateAndroidResourceDir:
  Skipping target "_GenerateAndroidResourceDir" because all output files are up-to-date with respect to the input files.
Target _GenerateCodeBehindForLayout:
  Skipping target "_GenerateCodeBehindForLayout" because it has no outputs.
Target _DefineBuildTargetAbis:
    Build target ABI: armeabi-v7a;x86
Target VectorDrawableCheckBuildToolsVersionTask:
    Checking Android SDK Build-tools version...
    Selected Android SDK Build Tools Path: /Users/myProjectFolder/Library/Developer/Xamarin/android-sdk-macosx/build-tools/27.0.3/
    Selected Android SDK Build Tools Version: 27.0.3
    Android SDK Build Tools Version: 27.0.3 meets minimum requirements for Vector Drawables. OK.
    Finished Checking Android SDK Build-tools version.
Target _UpdateAndroidResgen:
  Skipping target "_UpdateAndroidResgen" because all output files are up-to-date with respect to the input files.
Target _CreateAdditionalResourceCache:
  Skipping target "_CreateAdditionalResourceCache" because it has no outputs.
Target _GenerateJavaDesignerForComponent:
  Skipping target "_GenerateJavaDesignerForComponent" because all output files are up-to-date with respect to the input files.
Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target CoreCompile:
  Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
Target _CopyFilesMarkedCopyLocal:
    Touching "/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/obj/Debug/testHelloworld2.csproj.CopyComplete".
Target CopyFilesToOutputDirectory:
    testHelloworld2 -> /Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/bin/Debug/testHelloworld2.dll
Target IncrementalClean:
    Deleting file "/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/obj/Debug/linksrc/testHelloworld2.pdb".
    Deleting file "/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/obj/Debug/linksrc/Mono.Android.pdb".
    Deleting file "/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/bin/Debug/Mono.Android.pdb".
Target _CheckTargetFrameworks:
    /Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Animated.Vector.Drawable.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
    /Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Annotations.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
    /Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Compat.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
    /Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Core.UI.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
    /Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Core.Utils.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
    /Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Fragment.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
    /Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Media.Compat.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
    /Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.v7.AppCompat.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
    /Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Vector.Drawable.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
Done building target "_CheckTargetFrameworks" in project "testHelloworld2.csproj".
Target _CollectConfigFiles:
  Skipping target "_CollectConfigFiles" because all output files are up-to-date with respect to the input files.
Target _CopyConfigFiles:
  Skipping target "_CopyConfigFiles" because it has no outputs.
Target _CopyIntermediateAssemblies:
  Skipping target "_CopyIntermediateAssemblies" because all output files are up-to-date with respect to the input files.
Target _ConvertPdbFiles:
  Skipping target "_ConvertPdbFiles" because it has no outputs.
Target _CopyPdbFiles:
    Copying file from "bin/Debug/testHelloworld2.pdb" to "obj/Debug/linksrc/testHelloworld2.pdb".
    Copying file from "bin/Debug/Mono.Android.pdb" to "obj/Debug/linksrc/Mono.Android.pdb".
Target _CopyMdbFiles:
  Skipping target "_CopyMdbFiles" because it has no outputs.
Target _StripEmbeddedLibraries:
  Skipping target "_StripEmbeddedLibraries" because all output files are up-to-date with respect to the input files.
Target _LinkAssembliesNoShrink:
    Touching "obj/Debug/link.flag".
Target _AddStaticResources:
  Skipping target "_AddStaticResources" because all output files are up-to-date with respect to the input files.
Target _CreateAdditionalResourceCache:
  Skipping target "_CreateAdditionalResourceCache" because it has no outputs.
Target _GenerateAndroidAssetsDir:
  Skipping target "_GenerateAndroidAssetsDir" because it has no outputs.
Target _CreateBaseApk:
  Skipping target "_CreateBaseApk" because all output files are up-to-date with respect to the input files.
Target _CreateAdditionalResourceCache:
  Skipping target "_CreateAdditionalResourceCache" because it has no outputs.
Target _CompileJava:
  Skipping target "_CompileJava" because all output files are up-to-date with respect to the input files.
Target _CreateAdditionalResourceCache:
  Skipping target "_CreateAdditionalResourceCache" because it has no outputs.
Target _CompileToDalvikWithDx:
  Skipping target "_CompileToDalvikWithDx" because all output files are up-to-date with respect to the input files.
Target _CheckApkPerAbiFlag:
    Touching "obj/Debug/android/bin/apk_per_abi.flag".
Target _CopyPackage:
    Deleting file "bin/Debug/com.companyname.testHelloworld2.apk".
    Copying file from "/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/obj/Debug/android/bin/com.companyname.testHelloworld2.apk" to "bin/Debug/com.companyname.testHelloworld2.apk".
    Copying file from "/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/obj/Debug/android/bin/com.companyname.testHelloworld2-armeabi-v7a.apk" to "bin/Debug/com.companyname.testHelloworld2-armeabi-v7a.apk".
    Copying file from "/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/obj/Debug/android/bin/com.companyname.testHelloworld2-x86.apk" to "bin/Debug/com.companyname.testHelloworld2-x86.apk".
Target _ResolveAndroidSigningKey:
    Touching "obj/Debug/android_debug_keystore.flag".
Target _Sign:
    /usr/bin/keytool -list -alias androiddebugkey -storepass android -keypass android -keystore "/Users/myProjectFolder/.local/share/Xamarin/Mono for Android/debug.keystore" 
    Deleting file "bin/Debug/com.companyname.testHelloworld2-Signed.apk".
    /Users/myProjectFolder/Library/Developer/Xamarin/android-sdk-macosx/build-tools/27.0.3/zipalign 4 "/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/obj/Debug/android/bin/com.companyname.testHelloworld2.apk" "bin/Debug//com.companyname.testHelloworld2-Signed.apk" 
    /Users/myProjectFolder/Library/Developer/Xamarin/android-sdk-macosx/build-tools/27.0.3/zipalign 4 "/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/obj/Debug/android/bin/com.companyname.testHelloworld2-armeabi-v7a.apk" "bin/Debug//com.companyname.testHelloworld2-armeabi-v7a-Signed.apk" 
    Output file 'bin/Debug//com.companyname.testHelloworld2-armeabi-v7a-Signed.apk' exists
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2588,2): error MSB6006: "zipalign" exited with code 1.
Done building target "_Sign" in project "testHelloworld2.csproj" -- FAILED.

Done building project "testHelloworld2.csproj" -- FAILED.

Build FAILED.

/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Animated.Vector.Drawable.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Annotations.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Compat.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Core.UI.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Core.Utils.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Fragment.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Media.Compat.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.v7.AppCompat.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
/Users/myProjectFolder/Projects/testHelloworld2/testHelloworld2/testHelloworld2.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Android.Support.Vector.Drawable.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2588,2): error MSB6006: "zipalign" exited with code 1.
    9 Warning(s)
    1 Error(s)

Time Elapsed 00:00:05.07`

**Comment by dellis1972** [comment]
@RobertFrancis sorry thats not diagnostic output, so it doesn't contain the additional info we need. See [1] for how to turn it on in the IDE's.
Note the output will be HUGE so go to gist.github.com and past the output there. It makes it easier to read.. 

[1] https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output

**Comment by RobertFrancis** [comment]
Is this better ?

https://gist.github.com/RobertFrancis/83b12772ebb6be3237ec13de236effc0

**Comment by davidortinau** [comment]
@dellis1972 I've pinged the OP and others to try and provide you with answers.

**Comment by RobertFrancis** [comment]
Sorry for my stupidity. But could you clarify a few things...

> I guess try this from the command line
> 
> msbuild <project> /t:Install /v:diag > build.log

- Command line, meaning Terminal on Mac?
- Am I running this command at root ?
- Project, being the full path to the testHelloWorld2 sln file?
- Then I'm guessing the build.log will be dumped in this dir?

**Comment by jonpryor** [comment]
@RobertFrancis:

> * Command line, meaning Terminal on Mac?

Yes.

> * Am I running this command at root ?

You run it from the directory containing the `.csproj` of your Application project.

```bash
cd path/to/your/Solution/AppProject
msbuild AppProject.csproj /t:Install /v:diag > build.log
```

> * Project, being the full path to the testHelloWorld2 sln file?

`Project` is the path to the `AppProject.csproj` file, whatever project is responsible for creating your `.apk` file.

> * Then I’m guessing the build.log will be dumped in this dir?

Yes.

Once finished, you can run `open .` to open a Finder window from the current directory, at which point you can drag-and-drop `build.log` onto GitHub to upload it.

**Comment by curtisshipley** [comment]
Here is the gist:

https://gist.github.com/curtisshipley/1473bdf868eff77fc37c79fa02a0dc59

FWIW, I noticed that if I blow away the obj and bin directories, then rebuild, it succeeds. Doing a clean or rebuild all, doesn't work.

**Comment by RobertFrancis** [comment]
@jonpryor Thanks Jon, that was really helpful.

My gist is linked below.
https://gist.github.com/RobertFrancis/b5ce92b2591c80fd0d6f3d4bb2b6e493

Sorry for the slow response, I've been away. 
Has there been any progress with this?

**Comment by dellis1972** [comment]
@RobertFrancis I think I found a bug in our targets where the Abi specific apks are not being deleted, which would then probably cause this. I'll be taking a look this week

**Comment by dellis1972** [comment]
I think I have nailed down the problem here. Hopefully will have a PR up soon

**Comment by curtisshipley** [comment]
@dellis1972 In the mean time, is there a tweak we can make to the project file for this? Is it simply a matter of making sure the APKs are deleted?

**Comment by dellis1972** [comment]
PR is up https://github.com/xamarin/xamarin-android/pull/1567

**Comment by dellis1972** [comment]
@curtisshipley you could add a custom target to your csproj which runs before the `_Sign` target that deletes the files in question. 

```
<Target Name="_Workaround" BeforeTargets="_Sign"
         Inputs="$(MSBuildAllProjects);$(ApkFileIntermediate);$(_AndroidBuildPropertiesCache)"
	Outputs="$(ApkFileSigned)">
	<ItemGroup>
		<ApkAbiFilesSigned Include="$(ApkFileSigned)" />
		<ApkAbiFilesSigned Condition="'$(AndroidCreatePackagePerAbi)' == 'true' " Include="$(OutDir)$(_AndroidPackage)*-Signed.apk" />
	</ItemGroup>
	<Delete Files="%(ApkAbiFilesSigned.FullPath)" />
</Target>
```

That might fixup the issue in the mean time.

**Comment by curtisshipley** [comment]
@dellis1972  Thanks!!

**Comment by EmilAlipiev** [comment]
it is still not fixed. i am using latest update of VS 2017 pro version and I am getting this error very often.

**Comment by ThomasZeman** [comment]
Exact same problem here with see below and "Generate one package per selected ABI" enabled. However, Dellis1972 workaround fixed it for now.

Last output of build:

3>Deleting file "..\..\bin\Android\AnyCPU\Release\com.upp.pingpong.apk".
3>Copying file from "C:\reps\Upp.PingPong\Source\Upp.PingPong.Android\obj\Release\android\bin\com.upp.pingpong.apk" to "..\..\bin\Android\AnyCPU\Release\com.upp.pingpong.apk".
3>Copying file from "C:\reps\Upp.PingPong\Source\Upp.PingPong.Android\obj\Release\android\bin\com.upp.pingpong-armeabi.apk" to "..\..\bin\Android\AnyCPU\Release\com.upp.pingpong-armeabi.apk".
3>Copying file from "C:\reps\Upp.PingPong\Source\Upp.PingPong.Android\obj\Release\android\bin\com.upp.pingpong-armeabi-v7a.apk" to "..\..\bin\Android\AnyCPU\Release\com.upp.pingpong-armeabi-v7a.apk".
3>Copying file from "C:\reps\Upp.PingPong\Source\Upp.PingPong.Android\obj\Release\android\bin\com.upp.pingpong-x86.apk" to "..\..\bin\Android\AnyCPU\Release\com.upp.pingpong-x86.apk".
3>Copying file from "C:\reps\Upp.PingPong\Source\Upp.PingPong.Android\obj\Release\android\bin\com.upp.pingpong-arm64-v8a.apk" to "..\..\bin\Android\AnyCPU\Release\com.upp.pingpong-arm64-v8a.apk".
3>Touching "obj\Release\android_debug_keystore.flag".
3>C:\Program Files\Java\jdk1.8.0_121\\bin\keytool.exe -list -alias androiddebugkey -storepass android -keypass android -keystore "C:\Users\Tommi\AppData\Local\Xamarin\Mono for Android\debug.keystore" 
3>Deleting file "..\..\bin\Android\AnyCPU\Release\com.upp.pingpong-Signed.apk".
3>C:\Users\Tommi\AppData\Local\Android\Sdk\build-tools\27.0.3\zipalign.exe 4 "C:\reps\Upp.PingPong\Source\Upp.PingPong.Android\obj\Release\android\bin\com.upp.pingpong.apk" "..\..\bin\Android\AnyCPU\Release\\com.upp.pingpong-Signed.apk" 
3>C:\Users\Tommi\AppData\Local\Android\Sdk\build-tools\27.0.3\zipalign.exe 4 "C:\reps\Upp.PingPong\Source\Upp.PingPong.Android\obj\Release\android\bin\com.upp.pingpong-arm64-v8a.apk" "..\..\bin\Android\AnyCPU\Release\\com.upp.pingpong-arm64-v8a-Signed.apk" 
3>Output file '..\..\bin\Android\AnyCPU\Release\\com.upp.pingpong-arm64-v8a-Signed.apk' exists
3>"zipalign.exe" exited with code 1.
3>Done building project "Upp.PingPong.Android.csproj" -- FAILED.
3>Build FAILED.

Versions:

Microsoft Visual Studio Professional 2017 
Version 15.6.7
VisualStudio.15.Release/15.6.7+27428.2043
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

Visual F# Tools 10.1 for F# 4.1   00370-10000-65731-AA212
Microsoft Visual F# Tools 10.1 for F# 4.1

Application Insights Tools for Visual Studio Package   8.11.10402.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.2.0.10
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2017.3.1    Build 111.0.20171221.145902
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools

Tizen.Extension.Package Extension   1.0
Tizen.Extension.Package Visual Studio Extension Detailed Info

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27428.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.753 (f0f46392f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.96 (a702a9ceb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.9.1.24 (f62de47)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by dellis1972** [comment]
The issues is closed because the fix was merged into master. 
Unfortunately it was merged too late to get into the 15.7 build which just went to stable, as a result it will be in the next preview release 15.8. 

Because of this I posted a work around [1] for those of you wanting to use `apksigner`.
For those not wanting to use `apksigner` you can set the property `AndroidUseApkSigner` to false in your csproj

`<AndroudUseApkSigner>False</AndroudUseApkSigner>`

This will stop the new code path being used and the old `jarsigner` will be used in its place. This old code path should not have any issues.

[1] https://github.com/xamarin/xamarin-android/issues/1519#issuecomment-382025458

**Comment by EmilAlipiev** [comment]
15.7.0 is a trash. you shipped again something buggy. check xamarin forums, full of threads about it, people complaining and cursing

**Comment by FetFrumos** [comment]
@dellis1972 - Thank you, it it working.

**Comment by kyle-john** [comment]
@dellis1972 I just upgrade to vs 15.8 preview, but it still fails.

**Comment by JeroenBer** [comment]
I just installed 15.7.3 which came out today, same problem again, can't it be fixed in a 15.7.x service release ?
Deleting bin/obj did the trick for me

**Comment by dev8546** [comment]
For me the issue was when I had checked the option "Generate one package per selected ABI". The moment I unchecked zip align issues gone.. VS 2017 community edition

**Comment by FetFrumos** [comment]
Hello everybody, it does not work again(vs 15.7). Apk is builded and even installed. But the application crashes when it starts. Will it ever work ("Generate one package per selected ABI")? Three months have already passed.  Xamarin Team - your comment.
p.s. I did three times downgrade to Visual Studio 15.5.

**Comment by FetFrumos** [comment]
is there anyone here? it does not work for three months!!!

**Comment by dellis1972** [comment]
I am re-opening this issue based on user feedback. Is someone able to post a diagnostic build log which contains the error? I will try to repo again on 15.8.

If the application is crashing on startup that is probably a different issue. Please open a new issue and post the `add logcat` of the application startup.

**Comment by dellis1972** [comment]
I just tried to repo on Xamarin.Android 8.3.99.12 (the current alpha on MacOS) and it is working for me. The apk's are correctly signed when using 

`msbuild /t:Install /p:Configuration=Release /v:diag`

and the application starts on the device without any problems. Can anyone post any diagnostic output of the issue they are facing? 

@RobertFrancis the archiving in VSforMac is handled by the IDE at the moment. I believe there is currently a bug in the IDE around using `apksigner` . You might want to try `<AndroudUseApkSigner>False</AndroudUseApkSigner>` in your project until they fix that issue.

**Comment by FetFrumos** [comment]
Thank you for your message. I will prepare a repository with a demonstration of this issue. I use VS 15.7  for Windows.

**Comment by FetFrumos** [comment]
This is my repository with a demonstration of the [issue](https://github.com/FetFrumos/ApkSignerIssue)
This is simple standard project with one page. If I use "Aot compile" option I get error - "Apk failed to install Error:could not parse error string". If I disable this option than apk is work. 
For use my test project update option AndroidSigningKeyStore in ApkSignerIssue.Android.csproj - insert your path. File test.keystore is in folder test.
I use Android Api  26. Now I try Api 25. If AOT not working it is very bed. Without AOT Xamarin Forms +Android can not be used for commercial purposes.

**Comment by FetFrumos** [comment]
I try Api 25 - it is not work. I try use VS 15.5.7 and 15.8.0(preview) - with "AOT compile"  it is not work.
Without this option, XF+Android  can not be used - the first load of the app will take 8-10 seconds. Team - your comments.

**Comment by dellis1972** [comment]
@FetFrumos it sounds like you have a different issue from the `ZipAlign` problem listed on this issue. 

Do you have the build log for the "Apk failed to install Error:could not parse error string" issue? 

You might need to provide both the diagnostic build log and the output from `adb logcat` so we can look at the output the device is producing. We might need to open an new issue for the `Aot` problem so we can track that properly.

**Comment by RobertFrancis** [comment]
@dellis1972 ,

Please see this post for more information.
https://developercommunity.visualstudio.com/content/problem/253160/archive-for-publishing-generating-corrupt-apks.html

Why does rolling back my Xamarin.Android version stop the issue, if the issue is related to the VS for Mac IDE?

Since rolling back everything has been fine and I am somewhat hesitant to update anything at this point.

```
=== Visual Studio Community 2017 for Mac ===

Version 7.5 (build 1254)
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510010047

=== Xamarin.Android ===

Version: 8.1.5.0 (Visual Studio Community)
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Build Information ===

Release ID: 705001254
Git revision: 498923ea36d2c7fe440c4e4b8cfb75bd50bbd748
Build date: 2018-05-05 10:35:24-04
Xamarin addins: 219f1c4943b4693b837b4173dd10ea982a47c852
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.4
```

Thanks !

**Comment by EmilAlipiev** [comment]
@dellis1972  do you think are all these errors related to what you said?
https://github.com/xamarin/xamarin-android/issues/1651
https://github.com/xamarin/xamarin-android/issues/1760

**Comment by FetFrumos** [comment]
Hello everybody,
Downgrade to 15.5.7  working for me now. 
I do not know why this did not work right away, maybe I rebooted the computer. but now it works.
That's good - I was able to release an update my app.
And this is very sad - this is my fourth Downgrade in three months(starting from 15.6). 
Archiving the package does not work normally three months, three months, Karl!
I understand everything very difficult, but three months, with a bunch of reviews about these errors.
I do not know how you organized the product testing, but it's very sad. I lost a lot of time.

When will this work? Xamarin Team - your comments.

**Comment by FetFrumos** [comment]
I installed VS 15.7.4
With option:
 <AndroidUseApkSigner>False</AndroidUseApkSigner>
This is work for me. I hope the problem is solved. Thank you.

**Comment by EmilAlipiev** [comment]
This is so annoying problem still exist and every time we need to delete bin and obj folders.

**Comment by dellis1972** [comment]
If this is still a problem, can someone post on gist.github.com the
diagnostic build output showing the error and post the link here.
The scenario mentioned in the bug was fixed and is in the 15.8 release
(which is in the Alpha channel at the moment).

If you are using 15.7.x you need to use the work around
https://github.com/xamarin/xamarin-android/issues/1519#issuecomment-398999607

If there is another scenario where this is occurring we need more
information to replicate the issue.

If the error you are seeing is not producing a zip align error, when a new
issue should be opened with as much information as possible.

**Comment by gamesguru** [comment]
@EmilAlipiev 

Have you figured out what it is in the `bin` and `obj` directories that causes this hang-up?  I am also noticing your solution as acceptable, and am wondering what can be done on Xamarin's end to remedy this?  It seems to happen on the second or subsequent builds when dealing in large projects.

I understand giving a VS-integrated GUI option to delete bin and obj is sort of cheeky, but not being able to fix it for years while developers write custom shell and batch scripts to do _Xamarin_'s housekeeping locally?  That is also cheeky.

Hoping to see a solution to this one soon
