### ISSUE TITLE
UpdateAndroidResgen target is skipped on High Sierra and Win 10 after touching a resource file

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1962]
### Steps to Reproduce

1. Build project once.
2. Touch the layout file associated with the main activity of the project.
3. Build project again.

### Expected Behavior
_UpdateAndroidResgen runs again after a minor change to a resource file. I'm seeing this in d15-8 on Windows 10 and macOS sierra.

Sierra - _UpdateAndroidResgen runs (passed):
http://xqa.blob.core.windows.net/gist/sierra-build-out-c16e2eb482834b98993ea94a141c8ed5.txt

### Actual Behavior
_UpdateAndroidResgen does not run after a minor change to a resource file. I'm only seeing this in High Sierra macOS environments, and it does seem to be a regression in d15-8.

High Sierra - _UpdateAndroidResgen is skipped (failed):
http://xqa.blob.core.windows.net/gist/log-53f53861e0864f38a84e2bb99262e833.txt

### Version Information
https://gist.github.com/pjcollins/700067943fa1b5778c2559aa9d208535

> VS bug [#647693](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/647693)

**Comment by jonathanpeppers** [comment]
I think this could likely be fixed in: https://github.com/xamarin/xamarin-android/pull/1943/

Relevant log:
```
Target "_GenerateAndroidResourceDir: (TargetId:423)" in file "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets" from project "/Users/peter/Library/Caches/xqatmp/87b15a2e/Bug15162/Bug15162.csproj" (target "_UpdateAndroidResgen" depends on it):
Building target "_GenerateAndroidResourceDir" completely.
Input file "Resources/layout/Main.axml" is newer than output file "obj/Debug/res.flag".
...
Skipping Resources/layout/Main.axml its up to date (TaskId:394)
```

My fix in #1943 was that the `CopyIfChanged` task wasn't setting timestamps, which looks like it could cause this.

@pjcollins let me know if you can reproduce with latest master or not.

**Comment by pjcollins** [comment]
@jonathanpeppers I tried with the suggested monodroid master build[0] but I can still reproduce the scenario where this target is skipped:

http://xqa.blob.core.windows.net/gist/report-ba7d60928abe4742bd6757a969db3605.txt

[0] http://xamarin-jenkins.guest.corp.microsoft.com:8080/view/Xamarin.Android/job/monodroid-master/28/Azure/processDownloadRequest/monodroid/master/28/683f9478e2cdb94ec4088aeb9d189420c4d57162/package/xamarin.android-9.0.99-12.pkg

**Comment by jonathanpeppers** [comment]
@pjcollins I think we have a behavior change, and we need to make a small change to your test:

* Instead of updating the timestamp on the file
* Make a small content change -- maybe add spaces on the end or something

I think the new behavior is an improvement, using `CopyIfChanged` instead of the `Copy` task.

Let me know if the tests passes after this.

**Comment by pjcollins** [comment]
@jonathanpeppers unfortunately, adding some white space to the end of the file isn't changing the behavior for me. I forgot to add this to the initial report on Friday after discussing that possibility. 

I am also seeing that this target will be skipped in a rebuild after editing `Main.axml` myself (via VS Code or otherwise) and injecting an entirely new `<TextView>` element. This raises the concern around this issue, as it implies that valid layout changes in between partial builds won't be picked up.

The final strange aspect to this bug that I think requires further consideration is the fact that the behavior differs across OS type and versions when using the same repro and product versions.

**Comment by pjcollins** [comment]
@jonathanpeppers good find, I dropped in a `Xamarin.Android.Build.Tasks.dll` with this fix into a local installation and the test in question is passing again.
