### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getInstanceId()Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/iid/FirebaseInstanceId

### ISSUE THREAD

**Issue by hadigityat** [xamarin/xamarin-android#2921]
### Steps to Reproduce

1. Install Firebase package Xamarin.Firebase.Messaging 71.1502.0 - preview 1 (comes with additional related packages which are all in different versions)
2. Use getInstanceId() method from https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId
3. App crashes due to no NoSuchMethodError.

### Expected Behavior
getInstanceId() should be declared in FirebaseInstanceID

Also, I would expect Xamarin.Firebase packages would be available on the same version, and aligned with Xamarin.GooglePlayServices packages

### Actual Behavior
the method is not present in the Firebase.Iid.FirebaseInstanceID (71.1510.0 - preview 1) class in Xamarin, causing the crash

### Version Information

Visual Studio Community 2019 for Mac
Version 8.0 (build 3001)
Installation UUID: e54e9990-6782-4238-a6cd-797dff2cf7f1
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

Mono Framework MDK
Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

NuGet
Version: 4.8.2.5835

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Version: 5.6.0.25 (Visual Studio Community)
Hash: 50f75273
Branch: d16-0
Build date: 2019-03-05 11:50:33-0800

Xamarin.iOS
Version: 12.6.0.25 (Visual Studio Community)
Hash: 50f75273
Branch: d16-0
Build date: 2019-03-05 11:50:33-0800

Xamarin.Android
Version: 9.2.0.5 (Visual Studio Community)
Android SDK: /Users/Can/Downloads/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 29.0.0 rc1

Build Information: 
Mono: mono/mono/2018-08-rc@5ad371dab1b
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/master@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

Microsoft Mobile OpenJDK
Java SDK: /Users/Can/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-03-27 18:41:02 UTC

Xamarin Designer
Version: 4.17.4.414
Hash: 55b8d07ef
Branch: remotes/origin/d16-0
Build date: 2019-03-22 21:44:12 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 800003001
Git revision: 16b11d379aeff65cd1e81d3616c267ad4251ad36
Build date: 2019-03-28 13:14:24+00
Build branch: master
Xamarin extensions: efad41c7f410d8e6d43361236e0e778cf6f9b4a5

Operating System
Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

### Log File

{Java.Lang.NoSuchMethodError: No virtual method getInstanceId()Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/iid/FirebaseInstanceId; or its super classes (declaration of 'com.google.firebase.iid.FirebaseInstanceId' appears in /data/app/com.something.myapp-z5KWb0UKVI5dVl540C-t7A==/base.apk:classes5.dex)
  --- End of managed Java.Lang.NoSuchMethodError stack trace ---
java.lang.NoSuchMethodError: No virtual method getInstanceId()Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/iid/FirebaseInstanceId; or its super classes (declaration of 'com.google.firebase.iid.FirebaseInstanceId' appears in /data/app/com.something.mayapp-z5KWb0UKVI5dVl540C-t7A==/base.apk:classes5.dex)
	at epic.mychart.android.library.accountsettings.RegistrationIntentService.RegistrationIntentService.ReregisterTokenFromFirebase(RegistrationIntentService.java:144)
	at epic.mychart.android.library.accountsettings.RegistrationIntentService.onHandleWork(RegistrationIntentService.java:78)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
}

**Comment by Redth** [comment]
Please try the 71.*-preview2 releases, this should be fixed.

**Comment by hadigityat** [comment]
I am on 71.1510.0-preview2 and I see no fix. If you open the source of FirebaseInstanceId, you can see the method is not there. Still getting a crash.

**Comment by jayrlsw** [comment]
Is there a workaround for this? I am having the same issue.

**Comment by hadigityat** [comment]
Xamarin.Firebase.Iid version 71.1703.0-preview3 has the fix, if that helps

**Comment by marcelbeeker** [comment]
I've got this error Java.Lang.NoSuchMethodError
  Message=No virtual method postOnUiThread(Ljava/lang/Runnable;)V in class Lcom/microsoft/appcenter/push/Push; or its super classes (declaration of 'com.microsoft.appcenter.push.Push' after upgrading the Microsoft.AppCenter NuGet package from versions 4.1.0 to version 4.5.0 which is the latest version. My app crashes on my Samsung S8 device. In the emulator it's working OK. Does anyone a suggestion how to deal with this issue? Thanks in advance.

**Comment by jpobst** [comment]
Sounds like this is fixed for the reported `Xamarin.Firebase.Messaging`.

If it is happening for other packages, please file separate issues for them.
