### ISSUE TITLE
Visual Studio 2019 fails to start a debug session after migrating android-sdk platform-tools to 29.0.3

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-android#3627]
### Steps to Reproduce

1. Update android sdk platform-tools to latest version (29.0.3)
2. Launch any xamarin forms app in debug mode

### Expected Behavior

A debug session should start after the app has been deployed.

### Actual Behavior

The app is deployed but VS fails to start a debug session.
Error message : "Error Starting Application - Failed to forward ports"

No issue with previous version of platform-tools (29.0.2).

### Version Information

VS 2019 16.3.0 preview 3.0
VS 2019 16.2.5

**Comment by justinimel** [comment]
Also seeing this issue with the same setup.

**Comment by tranb3r** [comment]
The issue has been fixed in platform-tools 29.0.4.

**Comment by justinimel** [comment]
I just pulled the latest 29.0.4 and am still having the issue.

I will note that this issue only happens on VS for Mac.  Windows is fine.
