### ISSUE TITLE
Xamarin AndroidX Mediarouter can not build

### ISSUE THREAD

**Issue by hudaIT** [xamarin/xamarin-android#3930]
I get the following error after updating my **Xamarin.AndroidX.Mediarouter** package to **1.1.0-preview03**

Severity	Code	Description	Project	File	Line	Suppression State
Error		error: OnDynamicRoutesChangedListener is not public in DynamicGroupRouteController; cannot be accessed from outside package
		androidx.mediarouter.media.MediaRouteProvider.DynamicGroupRouteController.OnDynamicRoutesChangedListener	Verwaltungstool.Android	...\obj\Debug\100\android\src\mono\androidx\mediarouter\media\MediaRouteProvider_DynamicGroupRouteController_OnDynamicRoutesChangedListenerImplementor.java	8	

### Expected Behavior
Should build
### Actual Behavior
Does not build with Error
### Version Information

1. Version 16.4.0 Preview 5.0

2. Xamarin Forms Version : 4.5.0.1359-nightly

3. Xamarin AndroidX packages
```

<ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.CoordinatorLayout" Version="1.0.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Media" Version="1.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Fragment" Version="1.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common" Version="2.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Palette" Version="1.0.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.VectorDrawable.Animated" Version="1.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.Utils" Version="1.0.0-preview02" />
    <PackageReference Include="Xamarin.AndroidX.ViewPager" Version="1.0.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Annotation" Version="1.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Print" Version="1.0.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.CardView" Version="1.0.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.DrawerLayout" Version="1.0.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.CursorAdapter" Version="1.0.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.VectorDrawable" Version="1.1.0-preview03" />
    <PackageReference Include="Xamarin.Google.Android.Material" Version="1.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel" Version="2.1.0-preview03" 
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" Version="2.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Arch.Core.Common" Version="2.1.0-preview03" 
    <PackageReference Include="Xamarin.AndroidX.AsyncLayoutInflater" Version="1.0.0-preview03" 
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.UI" Version="1.0.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.CustomView" Version="1.0.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Core" Version="1.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Interpolator" Version="1.0.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.DocumentFile" Version="1.0.1-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Loader" Version="1.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.VersionedParcelable" Version="1.1.0-preview03" 
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.SlidingPaneLayout" Version="1.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Collection" Version="1.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.Arch.Core.Runtime" Version="2.1.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.RecyclerView" Version="1.0.0-preview03" />
    <PackageReference Include="Xamarin.AndroidX.SwipeRefreshLayout" Version="1.0.0-preview03" 
    <PackageReference Include="Xamarin.AndroidX.Transition" Version="1.2.0-preview03" />
  </ItemGroup>
```

**Comment by inforithmics** [comment]
I have the same problem (with Androidx Migration)

**Comment by Redth** [comment]
This should now be fixed in the latest preview.

**Comment by hudaIT** [comment]
> This should now be fixed in the latest preview.
When you mean 1.1.0-preview06 than it is not. :/

**Comment by seanrodda** [comment]
@Redth I am still receiving this error in the latest preview  (1.1.0-preview06)

**Comment by Redth** [comment]
Yup we can repro this and it is the very last item we are addressing before rc1 is released to nuget. Our goal is to have this out by end of week. Thanks for your patience!

**Comment by seanrodda** [comment]
That’s great! Thanks for the quick reply. Love all the work you’re doing with Xamarin Android

**Comment by Ryan-Palmer** [comment]
Hi guys, I just wondered if there is any update on this? I'm stuck half way through my AndroidX upgrade unfortunately. Thanks for the great work you have all been doing, cheers :)

**Comment by Ryan-Palmer** [comment]
For anyone else landing here, I think this is what we are waiting for: https://github.com/xamarin/AndroidX/issues/27

**Comment by seanrodda** [comment]
Does anyone know of a work around for this issue? Trying to add AndroidX Biometric support to my Xamarin Forms app

**Comment by VladislavAntonyuk** [comment]
Try to just dele this package reference. I was able to build with the latest RC1

**Comment by Ryan-Palmer** [comment]
I can confirm that the problem is fixed for me using the new RC1 which is available on nuget :) Cheers guys!

**Comment by hudaIT** [comment]
Yes solved however i got another error for missing Microsoft.Extensions.DependencyInjection.Abstractions Version 3.0.0
