### ISSUE TITLE
Debug symbols upload on Google Play Console for better crash information

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/xamarin-android#5378]
When we upload an app bundle or apk, below warning is returned from google play console. Question is what kind of source symbols should we or can we upload here? I am guessing that it is it not pdb files :) Is there a way for Xamarin.forms applications for android to get symbols and better crash information?

`This App Bundle contains native code, and you've not uploaded debug symbols. We recommend that you upload a symbol file to make your crashes and ANRs easier to analyse and debug.`
 
![image](https://user-images.githubusercontent.com/10422347/101300920-7f98a900-3837-11eb-87c9-e7cce1c89fb5.png)

**Comment by jonathanpeppers** [comment]
This was solved for obfuscated Java/Kotlin code here:

https://github.com/xamarin/xamarin-android/pull/5304

It doesn't look like we have solved this for native code, which would include AOT'd .NET assemblies.

**Comment by tbrentlong** [comment]
I'm seeing the same issue when uploading a bundle build via VS2019.  Is there a file somewhere that can be uploaded?  I also still get the deobfuscation message noted in 5186 even though I'm not using a code shrinker.

**Comment by jonathanpeppers** [comment]
@tbrentlong as mentioned in #5304, I think you would need to use `AndroidLinkMode=r8` to get the `mapping.txt` file.

Can you share a screenshot of the warning you get?

**Comment by Eversor** [comment]
I'm getting the same issue here, 
![image](https://user-images.githubusercontent.com/733699/115208154-8fd16680-a0fc-11eb-958b-3246480516fa.png)
![image](https://user-images.githubusercontent.com/733699/115208403-d030e480-a0fc-11eb-8e07-31476f0ad078.png)

Microsoft Visual Studio Community 2019
Version 16.7.6
VisualStudio.16.Release/16.7.6+30611.23
Microsoft .NET Framework
Version 4.8.04084

Xamarin   16.7.000.456 (d16-7-6@f8d55b6)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

**Comment by dellis1972** [comment]
VS 2019 16.7.x does not include the fix from #5304 since it was released before the fix was merged. 
You will need to be  on 16.9.x.
Also PR #5318 made it an "opt-in" feature. Which means you need to set the following in 
your release config in the csproj in order to activate it.

```
<AndroidProguardMappingFile>$(OutputPath)mapping.txt</AndroidProguardMappingFile>
```

**Comment by Eversor** [comment]
Thank you for the information, will try to update and post my findings... Do i need to activate Proguard code shrinking for the mappings to be outputted?

**Comment by dellis1972** [comment]
The `AndroidProguardMappingFile` only works with `r8` / `d8`.  It should output the mapping if those are set.

**Comment by plaili** [comment]
> It doesn't look like we have solved this for native code, which would include AOT'd .NET assemblies.

Is this issue with no debug symbols for native code tracked anywhere? Or will it be tracked here?

**Comment by EmilAlipiev** [comment]
@plaili https://github.com/xamarin/xamarin-android/issues/5342
https://github.com/xamarin/xamarin-android/pull/5304
https://github.com/xamarin/xamarin-android/pull/5318

Those are better. it actually already works like @dellis1972 suggested. I can see the file is generated.

**Comment by plaili** [comment]
> #5318

The mapping.txt is fine, it's generated here, too, but for native code there is still something missing as far as I understand it. At least I still see the warning.

**Comment by EmilAlipiev** [comment]
@dellis1972 @jonathanpeppers `<AndroidProguardMappingFile>$(OutputPath)mapping.txt</AndroidProguardMappingFile>`

this works fine in my local build. I can see the mapping.txt but in Azure Devops Pipelines, I am not seeing it it is generated. Is there any difference?

**Comment by lauxjpn** [comment]
There are a couple of issues in regards to the `AndroidProguardMappingFile` property.

### 1. The [AndroidProguardMappingFile docs](https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/building-apps/build-properties.md#androidproguardmappingfile) are incorrect in regards to the default value:

> The default value is `$(OutputPath)mapping.txt`.

There is no default value. If the property is not explicitly set, no mapping file will be created.

### 2. The [AndroidProguardMappingFile docs](https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/building-apps/build-properties.md#androidproguardmappingfile) are misleading in regards to the value of `$(OutputPath)mapping.txt`:

This value is not going to work as is. Unless you explicitly set the `OutputPath` property in your project file, it will not yet exist when you set the `AndroidProguardMappingFile` property. This then results in the `mapping.txt` file being output in the _current project root directory_ instead.

To fix this issue, I use the following:

```xml
<AndroidLinkTool>r8</AndroidLinkTool>
<AndroidProguardMappingFile>mapping.txt</AndroidProguardMappingFile>

<Target Name="FixAndroidProguardMappingFilePath" BeforeTargets="_CompileToDalvik">
    <PropertyGroup>
        <AndroidProguardMappingFile Condition="'$(AndroidProguardMappingFile)' != ''">$(OutputPath)mapping.txt</AndroidProguardMappingFile>
    </PropertyGroup>
</Target>

```

**Comment by jonathanpeppers** [comment]
@lauxjpn you should be able to use `$(OutputPath)` if you set your property after this line:
```xml
<Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />
<PropertyGroup>
  <AndroidProguardMappingFile>$(OutputPath)mapping.txt</AndroidProguardMappingFile>
</PropertyGroup>
```

It seems like we should maybe set `$(AndroidProguardMappingFile)` by default -- so you don't have to do this at all?

**Comment by lauxjpn** [comment]
@jonathanpeppers Ah, you're right that should work!

I think it makes sense to have `$(OutputPath)mapping.txt` as the default.

In case the mapping file generation is a performance hit, it might also make sense to introduce a simple flag property that when `true` would set the `$(OutputPath)mapping.txt` default. This flag property could then be set to `true` by default for either release or publish builds, and would otherwise be false.

**Comment by plaili** [comment]
I am trying to include the mapping.txt in my aab bundle:
`    <PropertyGroup>
        <AndroidProguardMappingFile>$(OutputPath)mapping.txt</AndroidProguardMappingFile>
        <AndroidBundleToolExtraArgs>--metadata-file=com.android.tools.obfuscation/mapping.txt:$(OutputPath)mapping.txt"</AndroidBundleToolExtraArgs>
    </PropertyGroup>
`
Unfortunately this does not include the mapping in the BUNDLE-METADATA folder of the aab. Has anyone got this to work?

**Comment by dellis1972** [comment]
@plaili ok looks like our Task which is responsible for calling the `build-bundle` command on `bundletool` does not support additional arguments. It seems that the `--metadata-file` argument has been added recently. 

The `AndroidBundleToolExtraArgs` is only used when we call `build-apks`. So we are going to need to add this feature.
I'll take a. look, we will probably add a `AndroidBundleMetaDataFile` ItemGroup which might look like

```
<ItemGroup>
<AndroidBundleMetaDataFile>com.android.tools.obfuscation/mapping.txt:$(OutputPath)mapping.txt</AndroidBundleMetaDataFile>
</ItemGroup>
```

I'll talk this over with @jonathanpeppers and see if we can come up with an easy way to handle this.

**Comment by dellis1972** [comment]
For reference

```
jar -jar bundletool.jar help build-bundle
Description:
    Builds an Android App Bundle from a set of Bundle modules provided as zip
    files.

    Note that the resource table, the AndroidManifest.xml and the resources must
    already have been compiled with aapt2 in the proto format.

Synopsis:
    bundletool build-bundle 
        --modules=<path/to/module1.zip,path/to/module2.zip,...>
        --output=<bundle.aab>
        [--config=<BundleConfig.pb.json>]
        [--metadata-file=<com.some.namespace/file-name:path/to/file>]
        [--overwrite]

Flags:
    --modules: The list of module files to build the final Android App Bundle
        from.

    --output: Path to the where the Android App Bundle should be built.

    --config: (Optional) Path to a JSON file that describes the configuration of
        the App Bundle. This configuration will be merged with BundleTool
        defaults.

    --metadata-file: (Optional) Specifies a file that will be included as
        metadata in the Android App Bundle. The format of the flag value is
        '<bundle-path>:<physical-file>' where 'bundle-path' denotes the file
        location inside the App Bundle's metadata directory, and 'physical-file'
        is an existing file containing the raw data to be stored. The flag can
        be repeated.

    --overwrite: (Optional) If set, any previous existing output will be
        overwritten.

```

**Comment by jonathanpeppers** [comment]
It seems like we could define these two by default if `AndroidLinkTool=r8`:

```xml
<!-- PropertyGroup -->
<AndroidProguardMappingFile>$(OutputPath)mapping.txt</AndroidProguardMappingFile>
<!-- ItemGroup-->
<AndroidAppBundleMetaDataFile Include="$(AndroidProguardMappingFile)" />
```

**Comment by dellis1972** [comment]
@plaili where did you find the value for the `com.android.tools.obfuscation` meta-data item?
I can't find any mention of it in the docs and I just tested am aab and google still complains about the mapping.txt file being missing.

**Comment by dellis1972** [comment]
Never mind, I found it should be `BUNDLE-METADATA/com.android.tools.build.obfuscation/proguard.map` by looking at an existing Java based app.

**Comment by plaili** [comment]
I am always confused about proguard.map vs. mapping.txt, but as you write they seem to be the same thing and must just be named accordingly in different situations.

**Comment by lauxjpn** [comment]
For APK builds, the `mapping.txt` file is currently not copied to the `PublishDir` when executing `dotnet publish`.
I therefore run the following target as a fix:

```xml
<!-- Copy mapping.txt file to publish directory. -->
<Target Name="PublishAndroidProguardMappingFile"
        AfterTargets="_CalculateAndroidFilesToPublish"
        BeforeTargets="CopyFilesToPublishDirectory"
        Inputs="$(AndroidProguardMappingFile)"
        Outputs="$(PublishDir)$([System.IO.Path]::GetFileName('$(AndroidProguardMappingFile)'))"
        Condition="'$(AndroidProguardMappingFile)' != '' And
                   Exists('$(AndroidProguardMappingFile)') And
                   ($(AndroidPackageFormats.Contains('apk')) Or '$(AndroidPackageFormat)' == 'apk')">
    <ItemGroup>
        <ResolvedFileToPublish Include="$(AndroidProguardMappingFile)"
                               RelativePath="$([System.IO.Path]::GetFileName('$(AndroidProguardMappingFile)'))" />
    </ItemGroup>
</Target>
```

**Comment by jonathanpeppers** [comment]
@lauxjpn can you send a PR for the `dotnet publish` issue? We don't really have a spec on what it's supposed to do -- we took a guess and copied the `.aab` and `.apk` files.

Seems like you could add that `mapping.txt` file to `@(_AndroidFilesToPublish)` here:

https://github.com/xamarin/xamarin-android/blob/f93d3d810279e7fad87063043fcc2c38b5c25bee/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Publish.targets#L22-L30

**Comment by lauxjpn** [comment]
@dellis1972 It might be worth copying the file to the publish directory independent of the used package format, because services like Microsoft AppCenter might depend on it for diagnostics.

According to [Android Deobfuscation: Uploading the mapping.txt file](https://docs.microsoft.com/en-us/appcenter/diagnostics/android-deobfuscation#uploading-the-mappingtxt-file), this should indeed be the case:

> ### App Center Portal
> 1. Download the `mapping.txt` file from your app module's build directory
> 2. Log into App Center and select your app
> 3. In the left menu, navigate to the **Diagnostics** section
> 4. Select **Mappings**
> 5. Click the **Upload mappings** button in the upper right
> 6. Fill in the Version Name and Version Code (these must match that build's Gradle configuration in order for the mapping to work for a particular build)
> 7. Upload the `mapping.txt` file from your app module's build directory.
> 8. Click the **Save** button.

However, for my Android apps in AppCenter, I only see the topics `Issues` and `Symbols` (the latter one referring to [Symbolicating Unmanaged Code Crashes](https://docs.microsoft.com/en-us/appcenter/diagnostics/unmanaged-code-crash-support), so not to `mapping.txt` files).

Maybe someone from the AppCenter team can clarify this.

**Comment by dellis1972** [comment]
@lauxjpn this code https://github.com/xamarin/xamarin-android/pull/6616/files#diff-72a69a14e7fbd5d8f65dce108bf7a0eca31fbbffaea6332ee4232ca020298b3dR27 will always make sure that the `mapping.txt` file ends up in the `publish` folder. It will also be auto included in the `.aab` as well.
