### ISSUE TITLE
System.Obsolete attribute used instead of ObsoletedOSPlatform attribute

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-android#7558]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022 17.4.1, .NET 7

### Description

I am using this property to get the installed app version:
```
public static string VersionString => (OperatingSystem.IsAndroidVersionAtLeast(33) ?
   Application.Context.PackageManager.GetPackageInfo(PackageName, PackageManager.PackageInfoFlags.Of(0)) :
   Application.Context.PackageManager.GetPackageInfo(PackageName, 0)).VersionName;
```

The old ([now deprecated](https://developer.android.com/reference/android/content/pm/PackageManager#getPackageInfo(android.content.pm.VersionedPackage,%20int))) `GetPackageInfo` method still emits this warning, even though `OperatingSystem.IsAndroidVersionAtLeast` is used:
`Warning	CS0618	'PackageManager.GetPackageInfo(string, PackageInfoFlags)' is obsolete: 'deprecated'	
`

This is because of this attribute:
`[System.Obsolete("deprecated")]`

I think this attribute should be used instead:
`[ObsoletedOSPlatform("android30.0")]`

I know this is rather nitpicking, but there might be other usages of the old `Obsolete` attribute that could be replaced with the `ObsoletedOSPlatform` attribute. In the PackageManager class alone there are also these methods currently annotated with the old attribute:
https://developer.android.com/reference/android/content/pm/PackageManager#addPreferredActivity(android.content.IntentFilter,%20int,%20android.content.ComponentName[],%20android.content.ComponentName)
https://developer.android.com/reference/android/content/pm/PackageManager#getPackageGids(java.lang.String,%20int)
https://developer.android.com/reference/android/content/pm/PackageManager#removePackageFromPreferred(java.lang.String)
https://developer.android.com/reference/android/content/pm/PackageManager#addPackageToPreferred(java.lang.String)

### Steps to Reproduce

1. Create new .NET 6 project
2. Add property as shown above
3. Build app / check warnings window

**Comment by jpobst** [comment]
`[ObsoletedOSPlatform]` was added in .NET 7, so if using `net7.0-android` this _should_ be working.  😁 

Fixed in https://github.com/xamarin/xamarin-android/issues/7234

**Comment by tipa** [comment]
I am using `net7.0-android33.0` but still see the warning.
As I mentioned, some methods are annotated with `ObsoletedOSPlatform` while others aren't (they are annotated with `System.Obsolete`).
I basically right-click on the method (`GetPackageInfo`) in VS22 and select "Go to Definition". It shows me this:
![image](https://user-images.githubusercontent.com/2863198/202227124-fcfbeabe-4fd5-4470-bddb-bb0d2fb5becf.png)

When I do the same for other methods (`GetInstallerPackageName`), I see this:
![image](https://user-images.githubusercontent.com/2863198/202227250-9a8d8768-28eb-4c3d-9c2c-77070160b53c.png)

The file appears to be this:
![image](https://user-images.githubusercontent.com/2863198/202227412-53e8cbee-782d-4961-ae6e-3a23d42827ff.png)

**Comment by jpobst** [comment]
> But there appears to be no overload for (int flags) in the Xamarin.Android references.

This appears to be a case of us making an unfortunate name choice a long time ago.

The original methods from Google are:
- `public abstract PackageInfo GetPackageInfo(VersionedPackage versionedPackage, int flags)`
- `public abstract PackageInfo GetPackageInfo(string packageName, int flags)`

We want our APIs to be a little easier to use, so we converted the `int flags` parameter to an enum called [`PackageInfoFlags`](https://learn.microsoft.com/en-us/dotnet/api/android.content.pm.packageinfoflags), so they now look like this:

- `public abstract PackageInfo GetPackageInfo(VersionedPackage versionedPackage, [GeneratedEnum] PackageInfoFlags flags)`
- `public abstract PackageInfo GetPackageInfo(string packageName, [GeneratedEnum] PackageInfoFlags flags)`

In API-33, it looks like Google has done the same thing we did and introduced new overloads that take an "enum-like" Java type:
- `public virtual PackageInfo GetPackageInfo(VersionedPackage versionedPackage, PackageManager.PackageInfoFlags flags)`
- `public virtual PackageInfo GetPackageInfo(string packageName, PackageManager.PackageInfoFlags flags)`

Note that instead of our enum `PackageInfoFlags` these use a Java class `PackageManager.PackageInfoFlags` which has the same name as our enum but is a different type.

Thus you have to look closer to see that methods that take the enum `PackageInfoFlags` (the `int flags` Java methods) are the ones that are deprecated, and the new methods that take the Java type `PackageManager.PackageInfoFlags` are not deprecated.

> This causes a compile error in our Xamarin.Forms apps on Azure DevOps windows-2022 images.

`[Obsolete]` does not produce an error, it produces a warning.  You likely have some form of `<TreatWarningsAsErrors>` or `<WarningsAsErrors>` in your project file.  You will need to suppress the warning using the regular C# mechanisms so your project does not treat it as an error.

**Comment by jahmai-ca** [comment]
> `[Obsolete]` does not produce an error, it produces a warning. You likely have some form of `<TreatWarningsAsErrors>` or `<WarningsAsErrors>` in your project file. You will need to suppress the warning using the regular C# mechanisms so your project does not treat it as an error.

We don't. We actually use [Obsolete] ourselves, which generates `warning CS0618` without any errors. This specific one gets converted to `Error CS0618: 'PackageManager.GetPackageInfo(string, PackageInfoFlags)' is obsolete: 'deprecated'` and I don't know why.

We're going to suppress it in code with `#pragma`, but ultimately we want to be able to call the appropriate version of GetPackageInfo since we target API 33 but support down to 23, and don't want to have to upgrade to NET8 to do that...

**Comment by jahmai-ca** [comment]
This may also apply to `PackageManager.QueryIntentActivities` with a similar issue of enum/int flags.

**Comment by jpobst** [comment]
This should be fixed as a result of:
- https://github.com/xamarin/xamarin-android/pull/7645
- https://github.com/xamarin/java.interop/pull/1068
