### ISSUE TITLE
`AddBindingsToCompile` is sometimes not run, breaking `_GenerateCompileDependencyCache` and incremental builds

### ISSUE THREAD

**Issue by Youssef1313** [xamarin/xamarin-android#8871]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

MSBuild 17.7

### Description

[msbuild.zip](https://github.com/xamarin/xamarin-android/files/14970421/msbuild.zip)

In the above binlog, see the build for `Uno.UI.BindingHelper.Android.netcoremobile.csproj` (ID 1387).

![image](https://github.com/xamarin/xamarin-android/assets/31348972/b136dbd4-78ff-4092-a4d5-60469879bcc9)

Here, some generated files (e.g, `Java.Interop.__TypeRegistrations`) aren't included in the hash.

And, for some reason, `ResolveReferences` is run, but `GenerateBindings` and `AddBindingsToCompile` are not.

![image](https://github.com/xamarin/xamarin-android/assets/31348972/a0847e58-788b-48c3-96eb-b985b7637d5d)

### Steps to Reproduce

-

**Comment by Youssef1313** [comment]
I feel like `GenerateBindings` should have `BeforeTargets="BeforeCompile"`

**Comment by Youssef1313** [comment]
@dellis1972 Do you think this is related to https://github.com/xamarin/xamarin-android/pull/8706 ? The version I'm running on doesn't seem to have this fix.

**Comment by dellis1972** [comment]
Probably, the issue is probably that the .cs files in the `generated` folder are missing, so they never get included.

**Comment by Youssef1313** [comment]
@dellis1972 Assuming that PR fixes it, could it be backported?

and which .NET 8 SDK contains the fix (if released already)?

**Comment by dellis1972** [comment]
Looks like its been back ported to 8.0.2 via https://github.com/xamarin/xamarin-android/commit/20d9605d54a1187614f9bf71baceb68f72c44608. Note sure the release date for 8.0.2 though.

**Comment by Youssef1313** [comment]
Regarding backporting, I meant to 7.x, if possible

**Comment by dellis1972** [comment]
I don't think we can, according to https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core. 7 is going out of support in a month.

**Comment by jpobst** [comment]
Seems like this is fixed in supported versions (.NET 8+).

**Comment by Youssef1313** [comment]
@jpobst It's still an issue for me. What I found so far is that `AddBindingsToCompile` and `GenerateBindings` are not run because `_ComputeFilesToPublishForRuntimeIdentifiers` is true in the specific broken build, causing `Microsoft.Android.Sdk.BuildOrder.targets` to not be imported. Still not sure if it's an issue in our side or on your side though.

**Comment by dellis1972** [comment]
Hmm this might be an inner build issue then. Afaik `_ComputeFilesToPublishForRuntimeIdentifiers` is only set when we do an inner build to collect outputs, it should not be running targets which delete files.

cc @jonathanpeppers what do you think?

**Comment by Youssef1313** [comment]
I opened https://github.com/xamarin/xamarin-android/issues/9007 with binlog and all info I could find.
